services:
  app:
    build: .
    container_name: queries-app
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - database

  database:
    image: postgres
    container_name: app-database
    restart: always
    ports:
      - 5423:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
